name: Deployment
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build with Maven
        # env:
          # RDS_HOSTNAME: ${{ secrets.RDS_HOSTNAME }}
          # RDS_PORT: ${{ secrets.RDS_PORT }}
          # RDS_DB_NAME: ${{ secrets.RDS_DB_NAME }}
          # RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          # RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          # JWT_SECRET: ${{ secrets.JWT_SECRET }}
          # JWT_TTL: ${{ secrets.JWT_TTL }}
          # SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          rm ./src/main/resources/application.properties
          mv ./src/main/resources/application-prod.properties ./src/main/resources/application.properties
          ./mvnw package -DskipTests
      - name: Upload application version
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./target/education-0.0.1-SNAPSHOT.jar 

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download application version
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: false
          application_name: edu-eb-application
          environment_name: edu-eb-environment
          version_label: ${{github.SHA}}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: education-0.0.1-SNAPSHOT.jar
